---
title: "Isolde Chapter 1"
author: "Isolde Lane-Shaw"
date: "6/11/2020"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

```{r packages}

#list packages to load
library("SpaDES")
library("raster")
library("sf")
library("rgdal")
library("ggplot2")
library("googledrive")

```


# Get Landscape Data

Here the LLC2005 raster layer of Canada is read in using the LandR prepInputs function. It will be used as the rasterToMatch layer for other spatial layers to reproject to match, and will also provide land cover classification data.

```{r LCC2005}

rasterToMatch <- LandR::prepInputsLCC() 

```

```{r studyArea, echo=FALSE}

nameAreaShapefile <- "RIA_fiveTSA.shp" #specify file name
folderUrlArea <- "https://drive.google.com/open?id=15ufr8h19veqtxH3Rd3Qj84jWHgdEs0PB" #give file location 
archiveArea <- "RIA_fiveTSA.zip" #give archive name

studyArea <- prepInputs(targetFile = nameAreaShapefile, 
                            url = folderUrlArea,
                            archive = archiveArea, 
                            alsoExtract = "similar",
                            destinationPath = paste0(getwd(),"/studyArea"),
                            fun = "raster::shapefile",
                            rasterToMatch = rasterToMatch,
                            overwrite = TRUE)

```


```{r cropAndMask}

landscapeRaster <- raster::crop(rasterToMatch,studyArea) #create landscapeRaster by cropping rasterToMatch to studyArea
landscapeRaster <- mask(landscapeRaster, studyArea) #mask landscapeRaster to studyArea
Plot(landscapeRaster) #double check landscapeRaster 

```


```{r getlandscapeValues}

# landscapeValues <- getValues(landscapeRaster) #get the values of the cells in the landscapeRaster
# landscapeValues <- landscapeValues[!is.na(landscapeValues)] #get rid of NAs
# #landscapeDF <- as.data.frame(table(landscapeValues)) #get counts of each category, put into dataframe

```


```{r plotLandscapeCategoryCounts, echo = FALSE}

# landCatPlot <- ggplot(landscapeDF) + geom_bar(aes(x=landscapeValues, y=Freq), stat="identity")
# print(landCatPlot) #create bar chart of freq of each landscape value category

```

# Get Bird Density Data

```{r getBirdDensityRaster}

nameBirdRaster <- "mosaic-OVEN-run3.tif" #specify file name
folderUrlBird <- "https://drive.google.com/file/d/1dOgCljSRI7sBKYtgOvxeFV5q_g5eBGMz/view?usp=sharing" #give file location 
archiveBird <- "birdDensityRasters.zip" #archive name

birdRaster <- prepInputs(targetFile = nameBirdRaster, 
                            url = folderUrlBird, 
                            archive = archiveBird, 
                            alsoExtract = "similar",
                            destinationPath = paste0(getwd(),"/birdRasterFiles"),
                            fun = "raster::raster",
                            rasterToMatch = landscapeRaster,
                            studyArea = studyArea,
                            overwrite = TRUE)

plot(birdRaster) #steve says Plot() is better

```

```{r getbirdDensityValues}

# birdDensityValues <- getValues(birdRaster) #get the values of the cells in the landscapeRaster
# landscapeValues <- birdDensityValues[!is.na(birdDensityValues)] #get rid of NAs
# #landscapeDF <- as.data.frame(table(landscapeValues)) #get counts of each category, put into dataframe

```

# Create dataframe of bird density by landscape

```{r getCellValues}

rasterStack <- stack(landscapeRaster, birdRaster)
cellValues <- as.data.frame(getValues(rasterStack))
cellValues <- na.omit(cellValues)
cellValues$LCC2005_V1_4a <- as.factor(cellValues$LCC2005_V1_4a)

```


```{r getClassCounts}

classCounts <- as.data.frame(table(cellValues[,1]))
colnames(classCounts) <- c("landCoverClass", "classCount")

```

```{r getMeanBirdDensity}



```